version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: meal-plan-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - FAT_SECRET_CLIENT_ID=${FAT_SECRET_CLIENT_ID}
      - FAT_SECRET_CLIENT_SECRET=${FAT_SECRET_CLIENT_SECRET}
    volumes:
      - ./:/app
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
