version: '3.8'

services:
  api:
    build: .
    container_name: meal-plan-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - MONGO_URI=mongodb://mongodb:27017/${DB_NAME}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
